version: "3.1"
services:

  postgres:
    image: postgres:9.6.1
    environment:
      POSTGRES_PASSWORD: xxx
      POSTGRES_DB: db

  wildfly:
    image: imixs/wildfly:1.2.5
    environment:
      WILDFLY_PASS: admin
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "xxx"
      POSTGRES_CONNECTION: "jdbc:postgresql://postgres/db"
    ports:
      - "8080:8080"
      - "9990:9990"
      - "8787:8787"
